spring:
    #数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.38:3306/testdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0 #指定redis实例
