spring:
    #数据源配置
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/testdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host:
    port:
    password:
    database: 0 #指定redis实例
